---
title: "CY350 Computer Networks"
lightbox: true
format: html
toc: false
listing:
  - id: content
    type: grid
    sort:
      - date
      - filename asc
    grid-columns: 5
    page-size: 50
    contents:
        - content/*.qmd
  - id: labs
    type: grid
    sort: date
    grid-columns: 5
    contents:
        - labs/*.qmd
---

This course provides an introduction to computer networks from both a theoretical and software design perspective. The goal is to provide the basic concepts necessary to understand the design and operation of computer networks and gain experience writing programs that use the network. Each level of the TCP/IP protocol stack is examined in detail with a heavy emphasis on socket programming, theoretical foundations, and cybersecurity implications.

::: {#content}
:::

## Lab Exercises

::: {#labs}
:::

## Course Resources

All the resources listed below are considered common knowledge and do not need to be cited.

### Where to get the textbook

- [Computer Networking (pearson.com)](https://www.pearson.com/en-us/subject-catalog/p/computer-networking/P200000003334/9780135928615)
- [Computer Networking: A Top-Down Approach: James Kurose: 9789356061316: Amazon.com: Books](https://www.amazon.com/Computer-Networking-Top-Down-James-Kurose/dp/9356061319)
- [Amazon.com: Computer Networking [RENTAL EDITION]: 9780136681557: James Kurose: Books](https://www.amazon.com/Computer-Networking-James-Kurose/dp/0136681557)
- See Modules > Course Resources

### Textbook Assistance Websites

- [Textbook Companion Website](https://media.pearsoncmg.com/ph/esm/ecs_kurose_compnetwork_8/cw/)
- [Author Website](https://gaia.cs.umass.edu/kurose_ross/index.php)

### Guides and Documentation

- [Python 3 Documentation](https://docs.python.org/3/)
- [Python f-strings](https://fstring.help/)
- [Python Notes for Professionals](https://goalkicker.com/PythonBook/)
- [Linux Notes for Professionals](https://goalkicker.com/LinuxBook/)
- [CY350 Linux Setup Guide](https://usma-eecs.github.io/linux-guide/)
- [CY350 Python Refresher](https://usma-eecs.github.io/python-refresher/)
- [Unofficial Instrtuctor Website: cy350.bhatia.dev](https://cy350.bhatia.dev/)

## Course Schedule

| Lesson                                              |  Day1  |  Day2  |  Assigned       | Due Date |
|-----------------------------------------------------|--------|--------|-----------------|----------|
|  1- Introduction to Networking                      | 07 Jan | 06 Jan | Usage Agreement | 11 Jan   |
|  2- Protocols, Layers, and Abstraction              | 09 Jan | 08 Jan | Problem Set 1   | 18 Jan   |
|  3- Assessing Terrain Conditions: Network Metrics   | 12 Jan | 13 Jan | Problem Set 2   | 25 Jan   |
|  4- Application Layer                               | 14 Jan | 15 Jan |                 |          |
|  5- HTTP and the Web                                | 20 Jan | 21 Jan |                 |          |
|  6- DNS and Email                                   | 30 Jan | 27 Jan | Problem Set 3   | 08 Feb   |
|  7- Socket Programming Lab                          | 04 Feb | 05 Feb | Problem Set 4   | 15 Feb   |
|  8- Transport Layer                                 | 09 Feb | 10 Feb | Problem Set 5   | 22 Feb   |
|  9- Reliable Data Transfer                          | 11 Feb | 12 Feb |                 |          |
| 10- Transmission Control Protocol                   | 18 Feb | 17 Feb | Problem Set 6   | 01 Mar   |
| 11- Flow and Congestion Control                     | 20 Feb | 19 Feb |                 |          |
| 12- UDP and QUIC                                    | 23 Feb | 24 Feb | Problem Set 7   | 08 Mar   |
| WPR1 Review                                         | 25 Feb | 26 Feb |                 |          |
| WPR1                                                | 02 Mar | 03 Mar | Project 1       | 22 Mar   |
| 13- Network Layer                                   | 04 Mar | 05 Mar |                 |          |
| 14- Internet Protocol v4                            | 09 Mar | 10 Mar | Problem Set 8   | 20 Mar   |
| 15- Internet Protocol v6                            | 11 Mar | 12 Mar |                 |          |
| 16- Routing Protocols- Link State, Distance Vector  | 16 Mar | 17 Mar |                 |          |
| 17- Control Plane                                   | 18 Mar | 19 Mar | Project 2       | 12 Apr   |
| 18- Link Layer                                      | 23 Mar | 24 Mar | Problem Set 9   | 06 Apr   |
| 19- Multiple Access Protocols & Switched LANs       | 25 Mar | 26 Mar |                 |          |
| 20- Wireless Networks                               | 07 Apr | 08 Apr | Problem Set 10  | 10 Apr   |
| 21- Bluetooth & Cellular Networks                   | 09 Apr | 10 Apr |                 |          |
| 22- Network Security Basics                         | 13 Apr | 14 Apr | Project 3       | 10 May   |
| 23- Transport Layer Security                        | 15 Apr | 16 Apr |                 |          |
| 24- VPNs and Wireless Network Security              | 20 Apr | 21 Apr |                 |          |
| WPR2                                                | 27 Apr | 28 Apr |                 |          |
| 25- Network Security Appliances                     | 29 Apr | 30 Apr |                 |          |
| 26- TBD                                             | 04 May | 05 May |                 |          |
| 27- TBD                                             | 06 May | 07 May |                 |          |
